name: "fiap-tech-challenge"
services:
  contacts-api:
    container_name: contacts-api
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        version: 1
    restart: always
    ports:
      - 8888:8080
    networks:
      - fiap-tech-challenge-fase2_network

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - prometheus-storage:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always
    ports:
      - 9090:9090
    networks:
      - fiap-tech-challenge-fase2_network
  
  grafana:
    container_name: grafana
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/dashboards:/var/lib/grafana/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: always
    ports:
      - 3000:3000
    networks:
      - fiap-tech-challenge-fase2_network
      
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - fiap-tech-challenge-fase2_network

volumes:
  postgres-db-volume:
    external: false
  grafana-storage:
    external: false
  prometheus-storage:
    external: false
  
networks:
  fiap-tech-challenge-fase2_network:
    driver: bridge